export const rawData = {
  success: true,
  result: {
    resource_id: '301000000A-000082-053',
    limit: 2000,
    total: 2000,
    fields: [
      {
        type: 'text',
        id: 'statistic_yyy',
      },
      {
        type: 'text',
        id: 'district_code',
      },
      {
        type: 'text',
        id: 'site_id',
      },
      {
        type: 'text',
        id: 'village',
      },
      {
        type: 'text',
        id: 'household_ordinary_total',
      },
      {
        type: 'text',
        id: 'household_business_total',
      },
      {
        type: 'text',
        id: 'household_single_total',
      },
      {
        type: 'text',
        id: 'household_ordinary_m',
      },
      {
        type: 'text',
        id: 'household_business_m',
      },
      {
        type: 'text',
        id: 'household_single_m',
      },
      {
        type: 'text',
        id: 'household_ordinary_f',
      },
      {
        type: 'text',
        id: 'household_business_f',
      },
      {
        type: 'text',
        id: 'household_single_f',
      },
    ],
    records: [
      {
        statistic_yyy: '統計年',
        district_code: '區域別代碼',
        site_id: '區域別',
        village: '村里名稱',
        household_ordinary_total: '共同生活戶_戶數',
        household_business_total: '共同事業戶_戶數',
        household_single_total: '單獨生活戶_戶數',
        household_ordinary_m: '共同生活戶_男',
        household_business_m: '共同事業戶_男',
        household_single_m: '單獨生活戶_男',
        household_ordinary_f: '共同生活戶_女',
        household_business_f: '共同事業戶_女',
        household_single_f: '單獨生活戶_女',
      },
      {
        statistic_yyy: '111',
        district_code: '65000010001',
        site_id: '新北市板橋區',
        village: '留侯里',
        household_ordinary_total: '445',
        household_business_total: '0',
        household_single_total: '237',
        household_ordinary_m: '660',
        household_business_m: '0',
        household_single_m: '108',
        household_ordinary_f: '737',
        household_business_f: '0',
        household_single_f: '129',
      },
      {
        statistic_yyy: '111',
        district_code: '65000010002',
        site_id: '新北市板橋區',
        village: '流芳里',
        household_ordinary_total: '376',
        household_business_total: '0',
        household_single_total: '248',
        household_ordinary_m: '551',
        household_business_m: '0',
        household_single_m: '109',
        household_ordinary_f: '657',
        household_business_f: '0',
        household_single_f: '139',
      },
      {
        statistic_yyy: '111',
        district_code: '65000010003',
        site_id: '新北市板橋區',
        village: '赤松里',
        household_ordinary_total: '268',
        household_business_total: '0',
        household_single_total: '233',
        household_ordinary_m: '400',
        household_business_m: '0',
        household_single_m: '96',
        household_ordinary_f: '436',
        household_business_f: '0',
        household_single_f: '137',
      },
      {
        statistic_yyy: '111',
        district_code: '65000010004',
        site_id: '新北市板橋區',
        village: '黃石里',
        household_ordinary_total: '341',
        household_business_total: '0',
        household_single_total: '193',
        household_ordinary_m: '538',
        household_business_m: '0',
        household_single_m: '85',
        household_ordinary_f: '574',
        household_business_f: '0',
        household_single_f: '108',
      },
      {
        statistic_yyy: '111',
        district_code: '65000010005',
        site_id: '新北市板橋區',
        village: '挹秀里',
        household_ordinary_total: '512',
        household_business_total: '0',
        household_single_total: '332',
        household_ordinary_m: '762',
        household_business_m: '0',
        household_single_m: '176',
        household_ordinary_f: '835',
        household_business_f: '0',
        household_single_f: '156',
      },
      {
        statistic_yyy: '111',
        district_code: '65000010006',
        site_id: '新北市板橋區',
        village: '湳興里',
        household_ordinary_total: '1300',
        household_business_total: '0',
        household_single_total: '947',
        household_ordinary_m: '2034',
        household_business_m: '0',
        household_single_m: '433',
        household_ordinary_f: '2174',
        household_business_f: '0',
        household_single_f: '514',
      },
      {
        statistic_yyy: '111',
        district_code: '65000010007',
        site_id: '新北市萬華區',
        village: '新興里',
        household_ordinary_total: '775',
        household_business_total: '0',
        household_single_total: '799',
        household_ordinary_m: '1166',
        household_business_m: '0',
        household_single_m: '348',
        household_ordinary_f: '1251',
        household_business_f: '0',
        household_single_f: '451',
      },
      {
        statistic_yyy: '111',
        district_code: '65000010008',
        site_id: '新北市蘆洲區',
        village: '社後里',
        household_ordinary_total: '1984',
        household_business_total: '0',
        household_single_total: '3637',
        household_ordinary_m: '3035',
        household_business_m: '0',
        household_single_m: '2459',
        household_ordinary_f: '3016',
        household_business_f: '0',
        household_single_f: '1178',
      },
      {
        statistic_yyy: '111',
        district_code: '65000010009',
        site_id: '桃園市中壢區',
        village: '香社里',
        household_ordinary_total: '1172',
        household_business_total: '0',
        household_single_total: '639',
        household_ordinary_m: '1895',
        household_business_m: '0',
        household_single_m: '327',
        household_ordinary_f: '1981',
        household_business_f: '0',
        household_single_f: '312',
      },
      {
        statistic_yyy: '111',
        district_code: '65000010010',
        site_id: '臺北市大安區',
        village: '中正里',
        household_ordinary_total: '1802',
        household_business_total: '0',
        household_single_total: '1387',
        household_ordinary_m: '2758',
        household_business_m: '0',
        household_single_m: '678',
        household_ordinary_f: '2883',
        household_business_f: '0',
        household_single_f: '709',
      },
    ],
  },
};
